// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: audit_tx.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditMsg_Phases int32

const (
	AuditMsg_PHASE_UNSPECIFIED  AuditMsg_Phases = 0 // 값이 안 세팅된 경우 구분용
	AuditMsg_PREPARE            AuditMsg_Phases = 1
	AuditMsg_AGGREGATED_PREPARE AuditMsg_Phases = 2
	AuditMsg_COMMIT             AuditMsg_Phases = 3
	AuditMsg_AGGREGATED_COMMIT  AuditMsg_Phases = 4
)

// Enum value maps for AuditMsg_Phases.
var (
	AuditMsg_Phases_name = map[int32]string{
		0: "PHASE_UNSPECIFIED",
		1: "PREPARE",
		2: "AGGREGATED_PREPARE",
		3: "COMMIT",
		4: "AGGREGATED_COMMIT",
	}
	AuditMsg_Phases_value = map[string]int32{
		"PHASE_UNSPECIFIED":  0,
		"PREPARE":            1,
		"AGGREGATED_PREPARE": 2,
		"COMMIT":             3,
		"AGGREGATED_COMMIT":  4,
	}
)

func (x AuditMsg_Phases) Enum() *AuditMsg_Phases {
	p := new(AuditMsg_Phases)
	*p = x
	return p
}

func (x AuditMsg_Phases) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditMsg_Phases) Descriptor() protoreflect.EnumDescriptor {
	return file_audit_tx_proto_enumTypes[0].Descriptor()
}

func (AuditMsg_Phases) Type() protoreflect.EnumType {
	return &file_audit_tx_proto_enumTypes[0]
}

func (x AuditMsg_Phases) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditMsg_Phases.Descriptor instead.
func (AuditMsg_Phases) EnumDescriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{2, 0}
}

type StandbyBSP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandbyBSP) Reset() {
	*x = StandbyBSP{}
	mi := &file_audit_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandbyBSP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandbyBSP) ProtoMessage() {}

func (x *StandbyBSP) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandbyBSP.ProtoReflect.Descriptor instead.
func (*StandbyBSP) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{0}
}

func (x *StandbyBSP) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HonestAuditor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HonestAuditor) Reset() {
	*x = HonestAuditor{}
	mi := &file_audit_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HonestAuditor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HonestAuditor) ProtoMessage() {}

func (x *HonestAuditor) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HonestAuditor.ProtoReflect.Descriptor instead.
func (*HonestAuditor) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{1}
}

func (x *HonestAuditor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuditMsg struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BlkNum              uint32                 `protobuf:"varint,1,opt,name=blkNum,proto3" json:"blkNum,omitempty"`
	PrevHash            string                 `protobuf:"bytes,2,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	MerkleRootHash      string                 `protobuf:"bytes,3,opt,name=MerkleRootHash,proto3" json:"MerkleRootHash,omitempty"`
	Time                string                 `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	TimeConstant        string                 `protobuf:"bytes,5,opt,name=timeConstant,proto3" json:"timeConstant,omitempty"`
	CurHash             string                 `protobuf:"bytes,6,opt,name=curHash,proto3" json:"curHash,omitempty"`
	LeaderID            string                 `protobuf:"bytes,7,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	Signature           []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	HonestAuditors      []*HonestAuditor       `protobuf:"bytes,9,rep,name=honestAuditors,proto3" json:"honestAuditors,omitempty"`
	PhaseNum            AuditMsg_Phases        `protobuf:"varint,10,opt,name=phaseNum,proto3,enum=msp.AuditMsg_Phases" json:"phaseNum,omitempty"`
	TxList              [][]byte               `protobuf:"bytes,11,rep,name=txList,proto3" json:"txList,omitempty"`
	Aborttransactionnum map[string]int32       `protobuf:"bytes,12,rep,name=aborttransactionnum,proto3" json:"aborttransactionnum,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuditMsg) Reset() {
	*x = AuditMsg{}
	mi := &file_audit_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditMsg) ProtoMessage() {}

func (x *AuditMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditMsg.ProtoReflect.Descriptor instead.
func (*AuditMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{2}
}

func (x *AuditMsg) GetBlkNum() uint32 {
	if x != nil {
		return x.BlkNum
	}
	return 0
}

func (x *AuditMsg) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *AuditMsg) GetMerkleRootHash() string {
	if x != nil {
		return x.MerkleRootHash
	}
	return ""
}

func (x *AuditMsg) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AuditMsg) GetTimeConstant() string {
	if x != nil {
		return x.TimeConstant
	}
	return ""
}

func (x *AuditMsg) GetCurHash() string {
	if x != nil {
		return x.CurHash
	}
	return ""
}

func (x *AuditMsg) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

func (x *AuditMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuditMsg) GetHonestAuditors() []*HonestAuditor {
	if x != nil {
		return x.HonestAuditors
	}
	return nil
}

func (x *AuditMsg) GetPhaseNum() AuditMsg_Phases {
	if x != nil {
		return x.PhaseNum
	}
	return AuditMsg_PHASE_UNSPECIFIED
}

func (x *AuditMsg) GetTxList() [][]byte {
	if x != nil {
		return x.TxList
	}
	return nil
}

func (x *AuditMsg) GetAborttransactionnum() map[string]int32 {
	if x != nil {
		return x.Aborttransactionnum
	}
	return nil
}

type Wnode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeID        string                 `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Publickey     []byte                 `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Seed          string                 `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`
	Proof         []byte                 `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"`
	Value         []byte                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wnode) Reset() {
	*x = Wnode{}
	mi := &file_audit_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wnode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wnode) ProtoMessage() {}

func (x *Wnode) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wnode.ProtoReflect.Descriptor instead.
func (*Wnode) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{3}
}

func (x *Wnode) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Wnode) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Wnode) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Wnode) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

func (x *Wnode) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *Wnode) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *Wnode) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	LeaderID      string                 `protobuf:"bytes,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	Member        []*Wnode               `protobuf:"bytes,3,rep,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Shard) Reset() {
	*x = Shard{}
	mi := &file_audit_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{4}
}

func (x *Shard) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Shard) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

func (x *Shard) GetMember() []*Wnode {
	if x != nil {
		return x.Member
	}
	return nil
}

type CommitteeMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	RoundNum      uint32                 `protobuf:"varint,2,opt,name=roundNum,proto3" json:"roundNum,omitempty"`
	Shards        []*Shard               `protobuf:"bytes,3,rep,name=shards,proto3" json:"shards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitteeMsg) Reset() {
	*x = CommitteeMsg{}
	mi := &file_audit_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitteeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteeMsg) ProtoMessage() {}

func (x *CommitteeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteeMsg.ProtoReflect.Descriptor instead.
func (*CommitteeMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{5}
}

func (x *CommitteeMsg) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CommitteeMsg) GetRoundNum() uint32 {
	if x != nil {
		return x.RoundNum
	}
	return 0
}

func (x *CommitteeMsg) GetShards() []*Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

type Committee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeID        string                 `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Publickey     []byte                 `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Committee) Reset() {
	*x = Committee{}
	mi := &file_audit_tx_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Committee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Committee) ProtoMessage() {}

func (x *Committee) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Committee.ProtoReflect.Descriptor instead.
func (*Committee) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{6}
}

func (x *Committee) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Committee) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Committee) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Committee) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

type RoundMsg struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Members        []*Committee           `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	RoundNum       uint32                 `protobuf:"varint,2,opt,name=roundNum,proto3" json:"roundNum,omitempty"`
	LeaderID       string                 `protobuf:"bytes,3,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	BaseTime       uint32                 `protobuf:"varint,4,opt,name=baseTime,proto3" json:"baseTime,omitempty"`
	ConsTime       uint32                 `protobuf:"varint,5,opt,name=consTime,proto3" json:"consTime,omitempty"`
	MerkleRootHash string                 `protobuf:"bytes,6,opt,name=MerkleRootHash,proto3" json:"MerkleRootHash,omitempty"`
	TxList         [][]byte               `protobuf:"bytes,7,rep,name=txList,proto3" json:"txList,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RoundMsg) Reset() {
	*x = RoundMsg{}
	mi := &file_audit_tx_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundMsg) ProtoMessage() {}

func (x *RoundMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundMsg.ProtoReflect.Descriptor instead.
func (*RoundMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{7}
}

func (x *RoundMsg) GetMembers() []*Committee {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoundMsg) GetRoundNum() uint32 {
	if x != nil {
		return x.RoundNum
	}
	return 0
}

func (x *RoundMsg) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

func (x *RoundMsg) GetBaseTime() uint32 {
	if x != nil {
		return x.BaseTime
	}
	return 0
}

func (x *RoundMsg) GetConsTime() uint32 {
	if x != nil {
		return x.ConsTime
	}
	return 0
}

func (x *RoundMsg) GetMerkleRootHash() string {
	if x != nil {
		return x.MerkleRootHash
	}
	return ""
}

func (x *RoundMsg) GetTxList() [][]byte {
	if x != nil {
		return x.TxList
	}
	return nil
}

type TransactionMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlkNum        uint64                 `protobuf:"varint,1,opt,name=blkNum,proto3" json:"blkNum,omitempty"`
	PrevHash      string                 `protobuf:"bytes,2,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	CurHash       string                 `protobuf:"bytes,3,opt,name=curHash,proto3" json:"curHash,omitempty"`
	Signature     string                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMsg) Reset() {
	*x = TransactionMsg{}
	mi := &file_audit_tx_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMsg) ProtoMessage() {}

func (x *TransactionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMsg.ProtoReflect.Descriptor instead.
func (*TransactionMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionMsg) GetBlkNum() uint64 {
	if x != nil {
		return x.BlkNum
	}
	return 0
}

func (x *TransactionMsg) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *TransactionMsg) GetCurHash() string {
	if x != nil {
		return x.CurHash
	}
	return ""
}

func (x *TransactionMsg) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type GossipMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Members       []*Committee           `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	RndMsg        *RoundMsg              `protobuf:"bytes,3,opt,name=rndMsg,proto3" json:"rndMsg,omitempty"`
	Rndblk        *AuditMsg              `protobuf:"bytes,4,opt,name=rndblk,proto3" json:"rndblk,omitempty"`
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMsg) Reset() {
	*x = GossipMsg{}
	mi := &file_audit_tx_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMsg) ProtoMessage() {}

func (x *GossipMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMsg.ProtoReflect.Descriptor instead.
func (*GossipMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{9}
}

func (x *GossipMsg) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GossipMsg) GetMembers() []*Committee {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GossipMsg) GetRndMsg() *RoundMsg {
	if x != nil {
		return x.RndMsg
	}
	return nil
}

func (x *GossipMsg) GetRndblk() *AuditMsg {
	if x != nil {
		return x.Rndblk
	}
	return nil
}

func (x *GossipMsg) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

var File_audit_tx_proto protoreflect.FileDescriptor

const file_audit_tx_proto_rawDesc = "" +
	"\n" +
	"\x0eaudit_tx.proto\x12\x03msp\"\x1c\n" +
	"\n" +
	"standbyBSP\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x1f\n" +
	"\rhonestAuditor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x83\x05\n" +
	"\bauditMsg\x12\x16\n" +
	"\x06blkNum\x18\x01 \x01(\rR\x06blkNum\x12\x1a\n" +
	"\bprevHash\x18\x02 \x01(\tR\bprevHash\x12&\n" +
	"\x0eMerkleRootHash\x18\x03 \x01(\tR\x0eMerkleRootHash\x12\x12\n" +
	"\x04time\x18\x04 \x01(\tR\x04time\x12\"\n" +
	"\ftimeConstant\x18\x05 \x01(\tR\ftimeConstant\x12\x18\n" +
	"\acurHash\x18\x06 \x01(\tR\acurHash\x12\x1a\n" +
	"\bleaderID\x18\a \x01(\tR\bleaderID\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\x12:\n" +
	"\x0ehonestAuditors\x18\t \x03(\v2\x12.msp.honestAuditorR\x0ehonestAuditors\x120\n" +
	"\bphaseNum\x18\n" +
	" \x01(\x0e2\x14.msp.auditMsg.PhasesR\bphaseNum\x12\x16\n" +
	"\x06txList\x18\v \x03(\fR\x06txList\x12X\n" +
	"\x13aborttransactionnum\x18\f \x03(\v2&.msp.auditMsg.AborttransactionnumEntryR\x13aborttransactionnum\x1aF\n" +
	"\x18AborttransactionnumEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"g\n" +
	"\x06Phases\x12\x15\n" +
	"\x11PHASE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPREPARE\x10\x01\x12\x16\n" +
	"\x12AGGREGATED_PREPARE\x10\x02\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x03\x12\x15\n" +
	"\x11AGGREGATED_COMMIT\x10\x04\"\xa5\x01\n" +
	"\x05wnode\x12\x16\n" +
	"\x06nodeID\x18\x01 \x01(\tR\x06nodeID\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1c\n" +
	"\tpublickey\x18\x04 \x01(\fR\tpublickey\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\tR\x04seed\x12\x14\n" +
	"\x05proof\x18\x06 \x01(\fR\x05proof\x12\x14\n" +
	"\x05value\x18\a \x01(\fR\x05value\"W\n" +
	"\x05shard\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bleaderID\x18\x02 \x01(\tR\bleaderID\x12\"\n" +
	"\x06member\x18\x03 \x03(\v2\n" +
	".msp.wnodeR\x06member\"b\n" +
	"\fcommitteeMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x1a\n" +
	"\broundNum\x18\x02 \x01(\rR\broundNum\x12\"\n" +
	"\x06shards\x18\x03 \x03(\v2\n" +
	".msp.shardR\x06shards\"i\n" +
	"\tcommittee\x12\x16\n" +
	"\x06nodeID\x18\x01 \x01(\tR\x06nodeID\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1c\n" +
	"\tpublickey\x18\x04 \x01(\fR\tpublickey\"\xe4\x01\n" +
	"\broundMsg\x12(\n" +
	"\amembers\x18\x01 \x03(\v2\x0e.msp.committeeR\amembers\x12\x1a\n" +
	"\broundNum\x18\x02 \x01(\rR\broundNum\x12\x1a\n" +
	"\bleaderID\x18\x03 \x01(\tR\bleaderID\x12\x1a\n" +
	"\bbaseTime\x18\x04 \x01(\rR\bbaseTime\x12\x1a\n" +
	"\bconsTime\x18\x05 \x01(\rR\bconsTime\x12&\n" +
	"\x0eMerkleRootHash\x18\x06 \x01(\tR\x0eMerkleRootHash\x12\x16\n" +
	"\x06txList\x18\a \x03(\fR\x06txList\"|\n" +
	"\x0etransactionMsg\x12\x16\n" +
	"\x06blkNum\x18\x01 \x01(\x04R\x06blkNum\x12\x1a\n" +
	"\bprevHash\x18\x02 \x01(\tR\bprevHash\x12\x18\n" +
	"\acurHash\x18\x03 \x01(\tR\acurHash\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\tR\tsignature\"\xb1\x01\n" +
	"\tgossipMsg\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12(\n" +
	"\amembers\x18\x02 \x03(\v2\x0e.msp.committeeR\amembers\x12%\n" +
	"\x06rndMsg\x18\x03 \x01(\v2\r.msp.roundMsgR\x06rndMsg\x12%\n" +
	"\x06rndblk\x18\x04 \x01(\v2\r.msp.auditMsgR\x06rndblk\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannelB\x04Z\x02./b\x06proto3"

var (
	file_audit_tx_proto_rawDescOnce sync.Once
	file_audit_tx_proto_rawDescData []byte
)

func file_audit_tx_proto_rawDescGZIP() []byte {
	file_audit_tx_proto_rawDescOnce.Do(func() {
		file_audit_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audit_tx_proto_rawDesc), len(file_audit_tx_proto_rawDesc)))
	})
	return file_audit_tx_proto_rawDescData
}

var file_audit_tx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_audit_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_audit_tx_proto_goTypes = []any{
	(AuditMsg_Phases)(0),   // 0: msp.auditMsg.Phases
	(*StandbyBSP)(nil),     // 1: msp.standbyBSP
	(*HonestAuditor)(nil),  // 2: msp.honestAuditor
	(*AuditMsg)(nil),       // 3: msp.auditMsg
	(*Wnode)(nil),          // 4: msp.wnode
	(*Shard)(nil),          // 5: msp.shard
	(*CommitteeMsg)(nil),   // 6: msp.committeeMsg
	(*Committee)(nil),      // 7: msp.committee
	(*RoundMsg)(nil),       // 8: msp.roundMsg
	(*TransactionMsg)(nil), // 9: msp.transactionMsg
	(*GossipMsg)(nil),      // 10: msp.gossipMsg
	nil,                    // 11: msp.auditMsg.AborttransactionnumEntry
}
var file_audit_tx_proto_depIdxs = []int32{
	2,  // 0: msp.auditMsg.honestAuditors:type_name -> msp.honestAuditor
	0,  // 1: msp.auditMsg.phaseNum:type_name -> msp.auditMsg.Phases
	11, // 2: msp.auditMsg.aborttransactionnum:type_name -> msp.auditMsg.AborttransactionnumEntry
	4,  // 3: msp.shard.member:type_name -> msp.wnode
	5,  // 4: msp.committeeMsg.shards:type_name -> msp.shard
	7,  // 5: msp.roundMsg.members:type_name -> msp.committee
	7,  // 6: msp.gossipMsg.members:type_name -> msp.committee
	8,  // 7: msp.gossipMsg.rndMsg:type_name -> msp.roundMsg
	3,  // 8: msp.gossipMsg.rndblk:type_name -> msp.auditMsg
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_audit_tx_proto_init() }
func file_audit_tx_proto_init() {
	if File_audit_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audit_tx_proto_rawDesc), len(file_audit_tx_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_tx_proto_goTypes,
		DependencyIndexes: file_audit_tx_proto_depIdxs,
		EnumInfos:         file_audit_tx_proto_enumTypes,
		MessageInfos:      file_audit_tx_proto_msgTypes,
	}.Build()
	File_audit_tx_proto = out.File
	file_audit_tx_proto_goTypes = nil
	file_audit_tx_proto_depIdxs = nil
}
