// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: msp_service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeID        string                 `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Publickey     []byte                 `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Seed          string                 `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`
	Proof         []byte                 `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"`
	Value         []byte                 `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_msp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_msp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_msp_service_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Node) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Node) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Node) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

func (x *Node) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *Node) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *Node) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type MemberMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LeaderID      string                 `protobuf:"bytes,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	StartBlk      uint32                 `protobuf:"varint,3,opt,name=startBlk,proto3" json:"startBlk,omitempty"`
	EndBlk        uint32                 `protobuf:"varint,4,opt,name=endBlk,proto3" json:"endBlk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberMsg) Reset() {
	*x = MemberMsg{}
	mi := &file_msp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberMsg) ProtoMessage() {}

func (x *MemberMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberMsg.ProtoReflect.Descriptor instead.
func (*MemberMsg) Descriptor() ([]byte, []int) {
	return file_msp_service_proto_rawDescGZIP(), []int{1}
}

func (x *MemberMsg) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *MemberMsg) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

func (x *MemberMsg) GetStartBlk() uint32 {
	if x != nil {
		return x.StartBlk
	}
	return 0
}

func (x *MemberMsg) GetEndBlk() uint32 {
	if x != nil {
		return x.EndBlk
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          []string               `protobuf:"bytes,1,rep,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_msp_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_msp_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_msp_service_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

var File_msp_service_proto protoreflect.FileDescriptor

const file_msp_service_proto_rawDesc = "" +
	"\n" +
	"\x11msp_service.proto\x12\x03msp\"\xa4\x01\n" +
	"\x04node\x12\x16\n" +
	"\x06nodeID\x18\x01 \x01(\tR\x06nodeID\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1c\n" +
	"\tpublickey\x18\x04 \x01(\fR\tpublickey\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\tR\x04seed\x12\x14\n" +
	"\x05proof\x18\x06 \x01(\fR\x05proof\x12\x14\n" +
	"\x05value\x18\a \x01(\fR\x05value\"|\n" +
	"\tMemberMsg\x12\x1f\n" +
	"\x05nodes\x18\x01 \x03(\v2\t.msp.nodeR\x05nodes\x12\x1a\n" +
	"\bleaderID\x18\x02 \x01(\tR\bleaderID\x12\x1a\n" +
	"\bstartBlk\x18\x03 \x01(\rR\bstartBlk\x12\x16\n" +
	"\x06endBlk\x18\x04 \x01(\rR\x06endBlk\"\x1d\n" +
	"\aAddress\x12\x12\n" +
	"\x04addr\x18\x01 \x03(\tR\x04addr2r\n" +
	"\x11MembershipService\x121\n" +
	"\rGetMembership\x12\x0e.msp.MemberMsg\x1a\x0e.msp.MemberMsg\"\x00\x12*\n" +
	"\n" +
	"GetAddress\x12\f.msp.Address\x1a\f.msp.Address\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_msp_service_proto_rawDescOnce sync.Once
	file_msp_service_proto_rawDescData []byte
)

func file_msp_service_proto_rawDescGZIP() []byte {
	file_msp_service_proto_rawDescOnce.Do(func() {
		file_msp_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msp_service_proto_rawDesc), len(file_msp_service_proto_rawDesc)))
	})
	return file_msp_service_proto_rawDescData
}

var file_msp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_msp_service_proto_goTypes = []any{
	(*Node)(nil),      // 0: msp.node
	(*MemberMsg)(nil), // 1: msp.MemberMsg
	(*Address)(nil),   // 2: msp.Address
}
var file_msp_service_proto_depIdxs = []int32{
	0, // 0: msp.MemberMsg.nodes:type_name -> msp.node
	1, // 1: msp.MembershipService.GetMembership:input_type -> msp.MemberMsg
	2, // 2: msp.MembershipService.GetAddress:input_type -> msp.Address
	1, // 3: msp.MembershipService.GetMembership:output_type -> msp.MemberMsg
	2, // 4: msp.MembershipService.GetAddress:output_type -> msp.Address
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msp_service_proto_init() }
func file_msp_service_proto_init() {
	if File_msp_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msp_service_proto_rawDesc), len(file_msp_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msp_service_proto_goTypes,
		DependencyIndexes: file_msp_service_proto_depIdxs,
		MessageInfos:      file_msp_service_proto_msgTypes,
	}.Build()
	File_msp_service_proto = out.File
	file_msp_service_proto_goTypes = nil
	file_msp_service_proto_depIdxs = nil
}
