// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.6.1
// source: test.proto

package __

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Join 요청
type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 참여 노드의 고유 ID
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`                   // 네트워크 주소
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`                   // 노드 리스닝 포트
	Publickey     string                 `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`         // 노드 공개키
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *JoinRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *JoinRequest) GetPublickey() string {
	if x != nil {
		return x.Publickey
	}
	return ""
}

// 커미티 정보 (Join 이후 스트리밍으로 내려옴)
type CommitteeInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ChannelId      string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`                  // 커미티 구성한 패브릭 채널 이름
	MemberIds      []string               `protobuf:"bytes,2,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`                  // 커미티 멤버 ID 목록
	LeaderMemberId string                 `protobuf:"bytes,3,opt,name=leader_member_id,json=leaderMemberId,proto3" json:"leader_member_id,omitempty"` // 커미티 리더 멤버 ID
	Timestamp      string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                   // 구성 시각
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommitteeInfo) Reset() {
	*x = CommitteeInfo{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitteeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteeInfo) ProtoMessage() {}

func (x *CommitteeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteeInfo.ProtoReflect.Descriptor instead.
func (*CommitteeInfo) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *CommitteeInfo) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *CommitteeInfo) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *CommitteeInfo) GetLeaderMemberId() string {
	if x != nil {
		return x.LeaderMemberId
	}
	return ""
}

func (x *CommitteeInfo) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

// 구성 요청
type CommitteeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // 참여 노드의 고유 ID
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`                   // 네트워크 주소
	Port          string                 `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`                   // 노드 리스닝 포트
	Publickey     string                 `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`         // 노드 공개키
	Channel       string                 `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`             // 패브릭 채널 이름
	Seed          []byte                 `protobuf:"bytes,6,opt,name=seed,proto3" json:"seed,omitempty"`                   // VRF에 사용되는 seed
	Proof         []byte                 `protobuf:"bytes,7,opt,name=proof,proto3" json:"proof,omitempty"`                 // 본인의 proof
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitteeRequest) Reset() {
	*x = CommitteeRequest{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitteeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteeRequest) ProtoMessage() {}

func (x *CommitteeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteeRequest.ProtoReflect.Descriptor instead.
func (*CommitteeRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *CommitteeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CommitteeRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *CommitteeRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *CommitteeRequest) GetPublickey() string {
	if x != nil {
		return x.Publickey
	}
	return ""
}

func (x *CommitteeRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CommitteeRequest) GetSeed() []byte {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *CommitteeRequest) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\tcommittee\x1a\x1bgoogle/protobuf/empty.proto\"l\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1c\n" +
	"\tpublickey\x18\x04 \x01(\tR\tpublickey\"\x95\x01\n" +
	"\rCommitteeInfo\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x02 \x03(\tR\tmemberIds\x12(\n" +
	"\x10leader_member_id\x18\x03 \x01(\tR\x0eleaderMemberId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\"\xb5\x01\n" +
	"\x10CommitteeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x03 \x01(\tR\x04port\x12\x1c\n" +
	"\tpublickey\x18\x04 \x01(\tR\tpublickey\x12\x18\n" +
	"\achannel\x18\x05 \x01(\tR\achannel\x12\x12\n" +
	"\x04seed\x18\x06 \x01(\fR\x04seed\x12\x14\n" +
	"\x05proof\x18\a \x01(\fR\x05proof2\x9b\x01\n" +
	"\x10CommitteeService\x12<\n" +
	"\x04Join\x12\x16.committee.JoinRequest\x1a\x18.committee.CommitteeInfo\"\x000\x01\x12I\n" +
	"\x10RequestCommittee\x12\x1b.committee.CommitteeRequest\x1a\x16.google.protobuf.Empty\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_test_proto_goTypes = []any{
	(*JoinRequest)(nil),      // 0: committee.JoinRequest
	(*CommitteeInfo)(nil),    // 1: committee.CommitteeInfo
	(*CommitteeRequest)(nil), // 2: committee.CommitteeRequest
	(*empty.Empty)(nil),      // 3: google.protobuf.Empty
}
var file_test_proto_depIdxs = []int32{
	0, // 0: committee.CommitteeService.Join:input_type -> committee.JoinRequest
	2, // 1: committee.CommitteeService.RequestCommittee:input_type -> committee.CommitteeRequest
	1, // 2: committee.CommitteeService.Join:output_type -> committee.CommitteeInfo
	3, // 3: committee.CommitteeService.RequestCommittee:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
