package packet

const (
	BLOCK_FIND_PACKET     = 11
	BLOCK_INFO_PACKET     = 12
	BLOCK_REQUEST_PACKET  = 13
	BLOCK_DATA_PACKET     = 14
	BLOCK_DATA_ACK_PACKET = 15
	BLOCK_FIN_PACKET      = 16
	CONTROL_PACKET        = 17
	NODE_INFO_PACKET      = 18
	PATH_INFO_PACKET      = 19
	PATH_INFO_ACK_PACKET  = 20
	FIN_PACKET            = 21
	FIN_ACK_PACKET        = 22
	AUDIT_MSG_PACKET      = 23
	AUDIT_MSG_ACK_PACKET  = 24
	PACKET_SIZE           = 1460000000 // maximum packet size (header + payload)
	PAYLOAD_SIZE          = 1024 // 1KB = SYMBOL SIZE, Block Data Size
)
