// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: audit_tx.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditMsg_Phases int32

const (
	AuditMsg_PREPARE            AuditMsg_Phases = 0
	AuditMsg_AGGREGATED_PREPARE AuditMsg_Phases = 1
	AuditMsg_COMMIT             AuditMsg_Phases = 2
	AuditMsg_AGGREGATED_COMMIT  AuditMsg_Phases = 3
)

// Enum value maps for AuditMsg_Phases.
var (
	AuditMsg_Phases_name = map[int32]string{
		0: "PREPARE",
		1: "AGGREGATED_PREPARE",
		2: "COMMIT",
		3: "AGGREGATED_COMMIT",
	}
	AuditMsg_Phases_value = map[string]int32{
		"PREPARE":            0,
		"AGGREGATED_PREPARE": 1,
		"COMMIT":             2,
		"AGGREGATED_COMMIT":  3,
	}
)

func (x AuditMsg_Phases) Enum() *AuditMsg_Phases {
	p := new(AuditMsg_Phases)
	*p = x
	return p
}

func (x AuditMsg_Phases) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditMsg_Phases) Descriptor() protoreflect.EnumDescriptor {
	return file_audit_tx_proto_enumTypes[0].Descriptor()
}

func (AuditMsg_Phases) Type() protoreflect.EnumType {
	return &file_audit_tx_proto_enumTypes[0]
}

func (x AuditMsg_Phases) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditMsg_Phases.Descriptor instead.
func (AuditMsg_Phases) EnumDescriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{2, 0}
}

type StandbyBSP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StandbyBSP) Reset() {
	*x = StandbyBSP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandbyBSP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandbyBSP) ProtoMessage() {}

func (x *StandbyBSP) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandbyBSP.ProtoReflect.Descriptor instead.
func (*StandbyBSP) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{0}
}

func (x *StandbyBSP) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type HonestAuditor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *HonestAuditor) Reset() {
	*x = HonestAuditor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HonestAuditor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HonestAuditor) ProtoMessage() {}

func (x *HonestAuditor) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HonestAuditor.ProtoReflect.Descriptor instead.
func (*HonestAuditor) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{1}
}

func (x *HonestAuditor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AuditMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlkNum         uint32           `protobuf:"varint,1,opt,name=blkNum,proto3" json:"blkNum,omitempty"`
	PrevHash       string           `protobuf:"bytes,2,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	MerkleRootHash string           `protobuf:"bytes,3,opt,name=MerkleRootHash,proto3" json:"MerkleRootHash,omitempty"`
	Time           string           `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	TimeConstant   string           `protobuf:"bytes,5,opt,name=timeConstant,proto3" json:"timeConstant,omitempty"`
	CurHash        string           `protobuf:"bytes,6,opt,name=curHash,proto3" json:"curHash,omitempty"`
	LeaderID       string           `protobuf:"bytes,7,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	Signature      []byte           `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	HonestAuditors []*HonestAuditor `protobuf:"bytes,9,rep,name=honestAuditors,proto3" json:"honestAuditors,omitempty"`
	PhaseNum       AuditMsg_Phases  `protobuf:"varint,10,opt,name=phaseNum,proto3,enum=msp.AuditMsg_Phases" json:"phaseNum,omitempty"`
	TxList         [][]byte         `protobuf:"bytes,11,rep,name=txList,proto3" json:"txList,omitempty"`
}

func (x *AuditMsg) Reset() {
	*x = AuditMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuditMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditMsg) ProtoMessage() {}

func (x *AuditMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditMsg.ProtoReflect.Descriptor instead.
func (*AuditMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{2}
}

func (x *AuditMsg) GetBlkNum() uint32 {
	if x != nil {
		return x.BlkNum
	}
	return 0
}

func (x *AuditMsg) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *AuditMsg) GetMerkleRootHash() string {
	if x != nil {
		return x.MerkleRootHash
	}
	return ""
}

func (x *AuditMsg) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AuditMsg) GetTimeConstant() string {
	if x != nil {
		return x.TimeConstant
	}
	return ""
}

func (x *AuditMsg) GetCurHash() string {
	if x != nil {
		return x.CurHash
	}
	return ""
}

func (x *AuditMsg) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

func (x *AuditMsg) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AuditMsg) GetHonestAuditors() []*HonestAuditor {
	if x != nil {
		return x.HonestAuditors
	}
	return nil
}

func (x *AuditMsg) GetPhaseNum() AuditMsg_Phases {
	if x != nil {
		return x.PhaseNum
	}
	return AuditMsg_PREPARE
}

func (x *AuditMsg) GetTxList() [][]byte {
	if x != nil {
		return x.TxList
	}
	return nil
}

type Wnode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID    string `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addr      string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port      string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Publickey []byte `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Channel   string `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *Wnode) Reset() {
	*x = Wnode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wnode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wnode) ProtoMessage() {}

func (x *Wnode) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wnode.ProtoReflect.Descriptor instead.
func (*Wnode) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{3}
}

func (x *Wnode) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Wnode) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Wnode) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Wnode) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

func (x *Wnode) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type Shard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID       string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	LeaderID string   `protobuf:"bytes,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	Member   []*Wnode `protobuf:"bytes,3,rep,name=member,proto3" json:"member,omitempty"`
}

func (x *Shard) Reset() {
	*x = Shard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shard) ProtoMessage() {}

func (x *Shard) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shard.ProtoReflect.Descriptor instead.
func (*Shard) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{4}
}

func (x *Shard) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Shard) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

func (x *Shard) GetMember() []*Wnode {
	if x != nil {
		return x.Member
	}
	return nil
}

type CommitteeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	RoundNum uint32   `protobuf:"varint,2,opt,name=roundNum,proto3" json:"roundNum,omitempty"`
	Shards   []*Shard `protobuf:"bytes,3,rep,name=shards,proto3" json:"shards,omitempty"`
}

func (x *CommitteeMsg) Reset() {
	*x = CommitteeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitteeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitteeMsg) ProtoMessage() {}

func (x *CommitteeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitteeMsg.ProtoReflect.Descriptor instead.
func (*CommitteeMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{5}
}

func (x *CommitteeMsg) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CommitteeMsg) GetRoundNum() uint32 {
	if x != nil {
		return x.RoundNum
	}
	return 0
}

func (x *CommitteeMsg) GetShards() []*Shard {
	if x != nil {
		return x.Shards
	}
	return nil
}

type Committee struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID    string `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addr      string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port      string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Publickey []byte `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`
}

func (x *Committee) Reset() {
	*x = Committee{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Committee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Committee) ProtoMessage() {}

func (x *Committee) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Committee.ProtoReflect.Descriptor instead.
func (*Committee) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{6}
}

func (x *Committee) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Committee) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Committee) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Committee) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

type RoundMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members        []*Committee `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	RoundNum       uint32       `protobuf:"varint,2,opt,name=roundNum,proto3" json:"roundNum,omitempty"`
	LeaderID       string       `protobuf:"bytes,3,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	BaseTime       uint32       `protobuf:"varint,4,opt,name=baseTime,proto3" json:"baseTime,omitempty"`
	ConsTime       uint32       `protobuf:"varint,5,opt,name=consTime,proto3" json:"consTime,omitempty"`
	MerkleRootHash string       `protobuf:"bytes,6,opt,name=MerkleRootHash,proto3" json:"MerkleRootHash,omitempty"`
	TxList         [][]byte     `protobuf:"bytes,7,rep,name=txList,proto3" json:"txList,omitempty"`
}

func (x *RoundMsg) Reset() {
	*x = RoundMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoundMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundMsg) ProtoMessage() {}

func (x *RoundMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundMsg.ProtoReflect.Descriptor instead.
func (*RoundMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{7}
}

func (x *RoundMsg) GetMembers() []*Committee {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *RoundMsg) GetRoundNum() uint32 {
	if x != nil {
		return x.RoundNum
	}
	return 0
}

func (x *RoundMsg) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

func (x *RoundMsg) GetBaseTime() uint32 {
	if x != nil {
		return x.BaseTime
	}
	return 0
}

func (x *RoundMsg) GetConsTime() uint32 {
	if x != nil {
		return x.ConsTime
	}
	return 0
}

func (x *RoundMsg) GetMerkleRootHash() string {
	if x != nil {
		return x.MerkleRootHash
	}
	return ""
}

func (x *RoundMsg) GetTxList() [][]byte {
	if x != nil {
		return x.TxList
	}
	return nil
}

type TransactionMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlkNum    uint64 `protobuf:"varint,1,opt,name=blkNum,proto3" json:"blkNum,omitempty"`
	PrevHash  string `protobuf:"bytes,2,opt,name=prevHash,proto3" json:"prevHash,omitempty"`
	CurHash   string `protobuf:"bytes,3,opt,name=curHash,proto3" json:"curHash,omitempty"`
	Signature string `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *TransactionMsg) Reset() {
	*x = TransactionMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMsg) ProtoMessage() {}

func (x *TransactionMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMsg.ProtoReflect.Descriptor instead.
func (*TransactionMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionMsg) GetBlkNum() uint64 {
	if x != nil {
		return x.BlkNum
	}
	return 0
}

func (x *TransactionMsg) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *TransactionMsg) GetCurHash() string {
	if x != nil {
		return x.CurHash
	}
	return ""
}

func (x *TransactionMsg) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type GossipMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    uint32       `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Members []*Committee `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	RndMsg  *RoundMsg    `protobuf:"bytes,3,opt,name=rndMsg,proto3" json:"rndMsg,omitempty"`
	Rndblk  *AuditMsg    `protobuf:"bytes,4,opt,name=rndblk,proto3" json:"rndblk,omitempty"`
	Channel string       `protobuf:"bytes,5,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *GossipMsg) Reset() {
	*x = GossipMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_audit_tx_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMsg) ProtoMessage() {}

func (x *GossipMsg) ProtoReflect() protoreflect.Message {
	mi := &file_audit_tx_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMsg.ProtoReflect.Descriptor instead.
func (*GossipMsg) Descriptor() ([]byte, []int) {
	return file_audit_tx_proto_rawDescGZIP(), []int{9}
}

func (x *GossipMsg) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *GossipMsg) GetMembers() []*Committee {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GossipMsg) GetRndMsg() *RoundMsg {
	if x != nil {
		return x.RndMsg
	}
	return nil
}

func (x *GossipMsg) GetRndblk() *AuditMsg {
	if x != nil {
		return x.Rndblk
	}
	return nil
}

func (x *GossipMsg) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

var File_audit_tx_proto protoreflect.FileDescriptor

var file_audit_tx_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x74, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x6d, 0x73, 0x70, 0x22, 0x1c, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x6e, 0x64, 0x62, 0x79,
	0x42, 0x53, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x41, 0x75, 0x64,
	0x69, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0xca, 0x03, 0x0a, 0x08, 0x61, 0x75, 0x64, 0x69, 0x74, 0x4d, 0x73,
	0x67, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6b, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x62, 0x6c, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x65,
	0x76, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x65,
	0x76, 0x48, 0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52,
	0x6f, 0x6f, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4d,
	0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75, 0x72, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x3a, 0x0a, 0x0e, 0x68, 0x6f, 0x6e,
	0x65, 0x73, 0x74, 0x41, 0x75, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x41, 0x75,
	0x64, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x0e, 0x68, 0x6f, 0x6e, 0x65, 0x73, 0x74, 0x41, 0x75, 0x64,
	0x69, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x68, 0x61, 0x73, 0x65, 0x4e, 0x75,
	0x6d, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x61, 0x75,
	0x64, 0x69, 0x74, 0x4d, 0x73, 0x67, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x73, 0x52, 0x08, 0x70,
	0x68, 0x61, 0x73, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x4c, 0x69, 0x73,
	0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0x50, 0x0a, 0x06, 0x50, 0x68, 0x61, 0x73, 0x65, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45,
	0x50, 0x41, 0x52, 0x45, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x47, 0x47, 0x52, 0x45, 0x47,
	0x41, 0x54, 0x45, 0x44, 0x5f, 0x50, 0x52, 0x45, 0x50, 0x41, 0x52, 0x45, 0x10, 0x01, 0x12, 0x0a,
	0x0a, 0x06, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x10, 0x02, 0x12, 0x15, 0x0a, 0x11, 0x41, 0x47,
	0x47, 0x52, 0x45, 0x47, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x10,
	0x03, 0x22, 0x7f, 0x0a, 0x05, 0x77, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e,
	0x65, 0x6c, 0x22, 0x57, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x77, 0x6e,
	0x6f, 0x64, 0x65, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x62, 0x0a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x22, 0x0a, 0x06, 0x73,
	0x68, 0x61, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x73,
	0x70, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x64, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72, 0x64, 0x73, 0x22,
	0x69, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x22, 0xe4, 0x01, 0x0a, 0x08, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x73,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x62, 0x61, 0x73,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x73, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4d, 0x65, 0x72, 0x6b, 0x6c,
	0x65, 0x52, 0x6f, 0x6f, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x4c,
	0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x06, 0x74, 0x78, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x7c, 0x0a, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6b, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x62, 0x6c, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x75, 0x72, 0x48, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x75, 0x72, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0xb1, 0x01, 0x0a, 0x09, 0x67, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74,
	0x65, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x72,
	0x6e, 0x64, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73,
	0x70, 0x2e, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x72, 0x6e, 0x64, 0x4d,
	0x73, 0x67, 0x12, 0x25, 0x0a, 0x06, 0x72, 0x6e, 0x64, 0x62, 0x6c, 0x6b, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x61, 0x75, 0x64, 0x69, 0x74, 0x4d, 0x73,
	0x67, 0x52, 0x06, 0x72, 0x6e, 0x64, 0x62, 0x6c, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_audit_tx_proto_rawDescOnce sync.Once
	file_audit_tx_proto_rawDescData = file_audit_tx_proto_rawDesc
)

func file_audit_tx_proto_rawDescGZIP() []byte {
	file_audit_tx_proto_rawDescOnce.Do(func() {
		file_audit_tx_proto_rawDescData = protoimpl.X.CompressGZIP(file_audit_tx_proto_rawDescData)
	})
	return file_audit_tx_proto_rawDescData
}

var file_audit_tx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_audit_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_audit_tx_proto_goTypes = []interface{}{
	(AuditMsg_Phases)(0),   // 0: msp.auditMsg.Phases
	(*StandbyBSP)(nil),     // 1: msp.standbyBSP
	(*HonestAuditor)(nil),  // 2: msp.honestAuditor
	(*AuditMsg)(nil),       // 3: msp.auditMsg
	(*Wnode)(nil),          // 4: msp.wnode
	(*Shard)(nil),          // 5: msp.shard
	(*CommitteeMsg)(nil),   // 6: msp.committeeMsg
	(*Committee)(nil),      // 7: msp.committee
	(*RoundMsg)(nil),       // 8: msp.roundMsg
	(*TransactionMsg)(nil), // 9: msp.transactionMsg
	(*GossipMsg)(nil),      // 10: msp.gossipMsg
}
var file_audit_tx_proto_depIdxs = []int32{
	2, // 0: msp.auditMsg.honestAuditors:type_name -> msp.honestAuditor
	0, // 1: msp.auditMsg.phaseNum:type_name -> msp.auditMsg.Phases
	4, // 2: msp.shard.member:type_name -> msp.wnode
	5, // 3: msp.committeeMsg.shards:type_name -> msp.shard
	7, // 4: msp.roundMsg.members:type_name -> msp.committee
	7, // 5: msp.gossipMsg.members:type_name -> msp.committee
	8, // 6: msp.gossipMsg.rndMsg:type_name -> msp.roundMsg
	3, // 7: msp.gossipMsg.rndblk:type_name -> msp.auditMsg
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_audit_tx_proto_init() }
func file_audit_tx_proto_init() {
	if File_audit_tx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_audit_tx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandbyBSP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_tx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HonestAuditor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_tx_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuditMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_tx_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wnode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_tx_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Shard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_tx_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitteeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_tx_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Committee); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_tx_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoundMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_tx_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_audit_tx_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_audit_tx_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_audit_tx_proto_goTypes,
		DependencyIndexes: file_audit_tx_proto_depIdxs,
		EnumInfos:         file_audit_tx_proto_enumTypes,
		MessageInfos:      file_audit_tx_proto_msgTypes,
	}.Build()
	File_audit_tx_proto = out.File
	file_audit_tx_proto_rawDesc = nil
	file_audit_tx_proto_goTypes = nil
	file_audit_tx_proto_depIdxs = nil
}
