// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: msp_service.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeID    string `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Addr      string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port      string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	Publickey []byte `protobuf:"bytes,4,opt,name=publickey,proto3" json:"publickey,omitempty"`
	Alive     bool   `protobuf:"varint,5,opt,name=alive,proto3" json:"alive,omitempty"`
	Channel   string `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msp_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_msp_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_msp_service_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Node) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Node) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *Node) GetPublickey() []byte {
	if x != nil {
		return x.Publickey
	}
	return nil
}

func (x *Node) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *Node) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type MemberMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes    []*Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	LeaderID string  `protobuf:"bytes,2,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	StartBlk uint32  `protobuf:"varint,3,opt,name=startBlk,proto3" json:"startBlk,omitempty"`
	EndBlk   uint32  `protobuf:"varint,4,opt,name=endBlk,proto3" json:"endBlk,omitempty"`
}

func (x *MemberMsg) Reset() {
	*x = MemberMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msp_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberMsg) ProtoMessage() {}

func (x *MemberMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msp_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberMsg.ProtoReflect.Descriptor instead.
func (*MemberMsg) Descriptor() ([]byte, []int) {
	return file_msp_service_proto_rawDescGZIP(), []int{1}
}

func (x *MemberMsg) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *MemberMsg) GetLeaderID() string {
	if x != nil {
		return x.LeaderID
	}
	return ""
}

func (x *MemberMsg) GetStartBlk() uint32 {
	if x != nil {
		return x.StartBlk
	}
	return 0
}

func (x *MemberMsg) GetEndBlk() uint32 {
	if x != nil {
		return x.EndBlk
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr []string `protobuf:"bytes,1,rep,name=addr,proto3" json:"addr,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msp_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_msp_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_msp_service_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

var File_msp_service_proto protoreflect.FileDescriptor

var file_msp_service_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x73, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x70, 0x22, 0x94, 0x01, 0x0a, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x61, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22,
	0x7c, 0x0a, 0x09, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1f, 0x0a, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x6d, 0x73,
	0x70, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x42, 0x6c, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x42, 0x6c, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6b, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6b, 0x22, 0x1d, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x32, 0x72, 0x0a, 0x11,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x31, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68,
	0x69, 0x70, 0x12, 0x0e, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4d,
	0x73, 0x67, 0x1a, 0x0e, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4d,
	0x73, 0x67, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x0c, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x1a, 0x0c, 0x2e, 0x6d, 0x73, 0x70, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x00,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msp_service_proto_rawDescOnce sync.Once
	file_msp_service_proto_rawDescData = file_msp_service_proto_rawDesc
)

func file_msp_service_proto_rawDescGZIP() []byte {
	file_msp_service_proto_rawDescOnce.Do(func() {
		file_msp_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_msp_service_proto_rawDescData)
	})
	return file_msp_service_proto_rawDescData
}

var file_msp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_msp_service_proto_goTypes = []interface{}{
	(*Node)(nil),      // 0: msp.node
	(*MemberMsg)(nil), // 1: msp.MemberMsg
	(*Address)(nil),   // 2: msp.Address
}
var file_msp_service_proto_depIdxs = []int32{
	0, // 0: msp.MemberMsg.nodes:type_name -> msp.node
	1, // 1: msp.MembershipService.GetMembership:input_type -> msp.MemberMsg
	2, // 2: msp.MembershipService.GetAddress:input_type -> msp.Address
	1, // 3: msp.MembershipService.GetMembership:output_type -> msp.MemberMsg
	2, // 4: msp.MembershipService.GetAddress:output_type -> msp.Address
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msp_service_proto_init() }
func file_msp_service_proto_init() {
	if File_msp_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msp_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msp_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msp_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msp_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msp_service_proto_goTypes,
		DependencyIndexes: file_msp_service_proto_depIdxs,
		MessageInfos:      file_msp_service_proto_msgTypes,
	}.Build()
	File_msp_service_proto = out.File
	file_msp_service_proto_rawDesc = nil
	file_msp_service_proto_goTypes = nil
	file_msp_service_proto_depIdxs = nil
}
